name: Deploy to GitHub Pages (Force Enable)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js (for any build if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Create _config.yml for Jekyll bypass
        run: |
          echo "plugins: []" > _config.yml
          echo "markdown: kramdown" >> _config.yml
          
      - name: Deploy to GitHub Pages using peaceiris action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
